# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='组名称')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default=123, max_length=32, verbose_name='代码'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(default=True, verbose_name='是否是菜单'),
        ),
    ]
