# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20171216_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=32, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(verbose_name='是否是菜单'),
        ),
    ]
