# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20171216_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='所属组'),
        ),
    ]
