# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permission_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='所属组'),
        ),
    ]
