# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20171216_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='所属菜单'),
            preserve_default=False,
        ),
    ]
